### PR TITLE
Fix for #214: Multiple autodiscounts only applies first discount.

### PR DESCRIPTION
**Pull request by kewljuice**
I commented out: 'break;' so that the script loops all the auto discounts and uses the discount with the highest value.

### CODE REVIEW

**Comment by agh1** [comment]
See comments at https://github.com/civicrm/org.civicrm.module.cividiscount/issues/214#issuecomment-582293735 and https://lab.civicrm.org/extensions/cividiscount/issues/1#note_24077 indicating that this change works.

For acceptance it would be better to delete the lines rather than commenting them out.

**Comment by kewljuice** [comment]
@agh1 I have made the adjustment

**Comment by agh1** [comment]
@kewljuice that looks a lot cleaner.  However, I looked through the "blame" on the existing code, and it looks like that `break` was added by PR #171 which was looking to address issue #167.  I'm concerned that you, @twomice, and @h-c-c might end up in a tug-of-war, so there may need to be a third solution to be sure that the applied discount is the counted one and the biggest autodiscount gets applied.

**Comment by freeform-sg** [comment]
Hi there - we're in a similar situation in that we need two auto discounts applied, however, we're not looking for the highest valued one, we want both. In our case, each one is linked to different price sets so there is no overlap between the discounts. The first is for the main event fee, and the second for an optional workshop, and the options for each are in different price sets.

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/merge_requests/215

**Pull request closed without merging**
