### PR TITLE
Change PHP keywords to comply with PSR2

### PR DESCRIPTION
**Pull request by mullikine**
Hi, I've changed a PHP keyword to comply with [this standard](https://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull) in PSR2. It's admittedly a small fix but I hope it helps!

### CODE REVIEW

**Comment by JoeMurray** [comment]
why didn't you merge this?

**Comment by seamuslee001** [comment]
@JoeMurray the CIviCRM styleguide conforms closer to Drupal's than this and that has words like TRUE FALSE etc in caps not lower case

**Comment by mlutfy** [comment]
There PRs are automated, we've been seeing them everywhere..

**Comment by JoeMurray** [comment]
Good reason not to merge. I am a bit surprised Drupal style guide doesn't
follow a PSR standard, but I guess not all standards 'take'.

@xurizaemon has met these guys as their office is near him. I think they
have ambitions to do more interesting and ambitious sorts  automated code
cleanup on open source projects.

Joe Murray from mobile

**Pull request closed without merging**
