### PR TITLE
Issue #194 Bug: Auto discounts not working for membership #194

### PR DESCRIPTION
**Pull request by chamilwijesooriya**

### CODE REVIEW

**Comment by chamilwijesooriya** [comment]
@MegaphoneJon please review

**Comment by mattwire** [comment]
@chamilwijesooriya Can you add some more detail to the PR about what is not working:
- How to reproduce the issue?
- How this fixes the issue?

**Comment by chamilwijesooriya** [comment]
Auto discounts feature is not working for memberships.

- CiviDiscount 3.3
- CiviCRM 5.1.1
- Auto populated with default civi data

Steps to reproduce:
1. Create a new discount
2. Add a single membership type 
3. In Automatic Discounts section enter the following:
    Entity : Contact
    API String: {"custom_2":"Single"}
4. Save 
5. Go to a any contact that has Marital Status as Single
6. Goto Memberships -> Add Membership
7. Choose the relevant membership type
8. Verify bug

NB:  custom_2 is Marital Status under Constituent Information

Possible Solution: 
In line 583 of cividiscount.php (cividiscount_civicrm_membershipTypeValue) (v3.3), change:
```
if (!empty($code)) {
    $discounts = $discountCalculator->getDiscounts();
}
```
to:
```
$discounts = $discountCalculator->getDiscounts();
if (empty($code))
    $discounts = $discountCalculator->autoDiscounts;
```

**Comment by elisseck** [comment]
I am also working on a project with the same issue, so I'm about to review this now and get it moving along.

**Comment by elisseck** [comment]
I just reviewed this PR:

This change makes sense to me, since we're just applying a method that already existed in a way that makes sense to apply it (e.g. getting automated discounts when there is no manual discount).

If you could add some brackets to that if statement, this PR would look good to merge to me.

* Explain ([`r-explain`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-explain))
    * __PASS__ : The goal/problem/solution have been adequately explained in the PR.
* Test results ([`r-test`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-test))
    * __UNREVIEWED__ 
    * __COMMENTS__: Do we have automated testing for CiviDiscount? I don't see a tests folder
* Code quality ([`r-code`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-code))
    * __ISSUE__: Code standards issue.
    * __COMMENTS__: @chamilwijesooriya Although technically optional here, please add brackets to your new if statement to adhere to the CiviCRM coding standards (mostly Drupal standards).
* Documentation ([`r-doc`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-doc))
    * __PASS__: The changes do not require documentation.
* Maintainability ([`r-maint`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-maint))
    * __PASS__: The change does not improve test coverage, but circumstances make it important to accept the change anyway.
    * __COMMENTS__: Since we don't have tests and we really want it to work as expected, I think we should pass it
* Run it ([`r-run`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-run))
    * __PASS__: I tested this patch with CiviCRM 5.1.2 and CiviDiscount 3.4 and verified that when adding a membership through the administrative UI and also when adding a membership through a live contribution page, my automatic discount was applied as expected. There were also no issues when there was no automatic discount, and a manual discount code still overrides the automatic discount as previously.
* User impact ([`r-user`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-user))
    * __PASS__: The change would be intuitive or unnoticeable for a majority of users who work with this feature.
* Technical impact ([`r-tech`](https://docs.civicrm.org/dev/en/latest/standards/review/#r-tech))
    * __PASS__: The change preserves compatibility with existing callers/code/downstream.
    * __COMMENTS__: We're just applying a method that already exists in a way that makes sense, so it shouldn't have any adverse affects.

**Comment by elisseck** [comment]
Thanks! Looks good to me. @MegaphoneJon, @mattwire any other thoughts? Appears to be a good fix to me.

**Comment by mattwire** [comment]
@elisseck No further thoughts from me.  I haven't tested it but it doesn't look like a major change so if others are happy then I think it's ok.

**Comment by MegaphoneJon** [comment]
No further thoughts here! I was going to review it because Chamil is new to the community and I want to be welcoming, but I don't have a use case that involves this, so your review is certainly better than mine.

**Pull request merged**
