### PR TITLE
Retrieve ID of Administer menu item from passed params

### LINKED ISSUE #208: Retrieve ID of Administer menu item from passed params
When this Extension is in use in WordPress Multisite, the "CiviDiscount" is improperly added to the CiviCRM Navigation Menu when the `domain_id` is not the primary one.

The reason is that `CRM_Core_DAO::getFieldValue()` does not default to the current `domain_id` and returns the first item that it finds - which is the menu item for the primary `domain_id`. This causes the "CiviDiscount" menu item to be improperly added.

The `$params` passed to `cividiscount_civicrm_navigationMenu()` do however contain the correct menu data, so searching the array produces the correct ID for the "Administer" menu.

FWIW, it seems that this is a common way of finding the Administer menu item - [CiviRules does it the same way](https://lab.civicrm.org/extensions/civirules/merge_requests/9) and suffers from the same problem.

### PR DESCRIPTION
**Pull request by christianwach**
Fixes #208

### CODE REVIEW

**Comment by colemanw** [comment]
Agree. Good change.

**Comment by christianwach** [comment]
Thanks for the quick merge @colemanw

**Comment by nganivet** [comment]
@colemanw Since this could be leveraged by multiple extensions, could we roll it up in a helper method in either core or civix (and of course document it in the developer guide) ? The current menu system is limited and really hard to work with, if all extensions only used a  few helper methods to deal with the menu system then this would facilitate a future refactor in core.

**Comment by christianwach** [comment]
@nganivet I agree that there is a commonality between Extensions when it comes to this sort of thing. Somehow the DB lookup method has become widespread.

I opened an [issue in Core](https://lab.civicrm.org/dev/core/issues/476) for the wider question of whether `CRM_Core_DAO::getFieldValue()` should default to current `domain_id` when the FK exists. This issue may be wider than simply querying for menu items as I'd imagine there are other places where a query like this might return the wrong value.

**Comment by christianwach** [comment]
One more thought: this happens to be a simple case of looking for a top-level menu so the loop is equally simple. Should the choice be helper method(s) as you suggest @nganivet then presumably there would also have to be a recursive helper method to retrieve nested values.

**Comment by nganivet** [comment]
**_cividiscount_civix_insert_navigation_menu** is a helper function I created and contributed to civix, great if it can be applied to this use case. I have not checked if it is documented the developer manual, but it should be if not.

Also, I understand Tim has the ability to scan all published extensions , it might be worth scanning these for calls to the DAO function and asking the extension author to switch to the helper method then.

@colemanw I do not think that the DAO function should automatically insert the domain_id in the query: the DAO is a database access layer, it is supposed to be 'dumb' and this is a business construct so should be addressed in the BAO. Let's keep the architecture clean.

**Pull request merged**
