### PR TITLE
issue with cleanMoney

### PR DESCRIPTION
**Pull request by jaapjansma**
There is an issue with thousand Seperators, see: https://lab.civicrm.org/dev/core/issues/584#note_11756

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I believe this is the correct fix - @monishdeb @mattwire any input?

**Comment by monishdeb** [comment]
Also ensured that it corrects the original issue #99

**Comment by monishdeb** [comment]
Merging now.

**Comment by eileenmcnaughton** [comment]
thanks @monishdeb  & @jaapjansma for getting to the bottom of this!

**Pull request merged**
